### ISSUE TITLE
🐛 Selecting "New Cluster" causes distro section of configfile to be overwritten

### ISSUE THREAD

**Issue by cloudymax** [small-hack/smol-k8s-lab#132]
## Describe the Bug

As a user with a k3s config that has lots of kubelet args, I prefer to configure all of them via the config file like so:

```yaml
# which distros of Kubernetes to deploy. Options: kind, k3s, k3d
# NOTE: only kind and k3d are available on macOS at this time
k8s_distros:
  k3s:
    # set to true to enable deploying a Kubernetes cluster using k3s
    enabled: true
    # if k8s_distro set to k3s/k3d, you can add an array of extra arguments to pass
    # to the k3s install script as a k3s.yaml file. If you enable cilium, we
    # automatically pass in flannel-backend: none and disable-network-policy: true
    k3s_yaml:
      # if you enable MetalLB, we automatically add servicelb to the disable list
      # enables encryption at rest for Kubernetes secrets
      secrets-encryption: true
      node-external-ip: 100.64.0.1
      # disables traefik so we can enable ingress-nginx, remove if you're using traefik
      disable:
      - traefik
      - servicelb
      node-label:
      - ingress-ready=true
      kubelet-arg:
      - max_pods=150
      - node-ip=192.168.50.100
      - cpu-manager-policy=static
      - kube-reserved=cpu=1,memory=2Gi,ephemeral-storage=1Gi
      - system-reserved=cpu=1,memory=2Gi,ephemeral-storage=1Gi
    nodes:
      control_plane: 1
      workers: 0
```

When I launch the TUI and select "New Cluster", my config file is overwritten to the following:

```yaml
# which distros of Kubernetes to deploy. Options: kind, k3s, k3d
# NOTE: only kind and k3d are available on macOS at this time
k8s_distros:
  k3s:
    # set to true to enable deploying a Kubernetes cluster using k3s
    enabled: true
    # if k8s_distro set to k3s/k3d, you can add an array of extra arguments to pass
    # to the k3s install script as a k3s.yaml file. If you enable cilium, we
    # automatically pass in flannel-backend: none and disable-network-policy: true
    k3s_yaml:
      # if you enable MetalLB, we automatically add servicelb to the disable list
      # enables encryption at rest for Kubernetes secrets
      secrets-encryption: true
      node-external-ip: 100.64.0.1
      # disables traefik so we can enable ingress-nginx, remove if you're using traefik
      disable:
      - traefik
      node-label:
      - ingress-ready=true
      kubelet-arg:
      - max_pods=150
    nodes:
      control_plane: 1
      workers: 0
```

However there is no issue if only using the cli

### Steps to Reproduce Bug
1. add some kubelet args to your config file
2. launch the tui
3. select "New Cluster"
4. Exit the TUI
5. Inspect your config file

#### Expected behavior
I would assume that the data from the config file would be loaded into the tui on init

## User info (please complete the following information):
 - OS release: `Debian12`
 - Kubernetes distro: `k3s`
 - Version of `smol-k8s-lab`: v2.0.0
 - Config file contents: see above

**Comment by jessebot** [comment]
Thanks for reporting this! I'll take a look tonight!

**Comment by jessebot** [comment]
fixing in #133

**Comment by cloudymax** [comment]
Unfortunately it's only mostly fixed, options that contain more than one comma get split prematurely:|

```yaml
# which distros of Kubernetes to deploy. Options: kind, k3s, k3d
# NOTE: only kind and k3d are available on macOS at this time
k8s_distros:
  k3s:
    # set to true to enable deploying a Kubernetes cluster using k3s
    enabled: true
    # if k8s_distro set to k3s/k3d, you can add an array of extra arguments to pass
    # to the k3s install script as a k3s.yaml file. If you enable cilium, we
    # automatically pass in flannel-backend: none and disable-network-policy: true
    k3s_yaml:
      # if you enable MetalLB, we automatically add servicelb to the disable list
      # enables encryption at rest for Kubernetes secrets
      secrets-encryption: true
      node-external-ip: 100.64.0.1
      # disables traefik so we can enable ingress-nginx, remove if you're using traefik
      disable:
      - traefik
      - servicelb
      node-label:
      - ingress-ready=true
      kubelet-arg:
      - max_pods=150
      - node-ip=192.168.50.100
      - cpu-manager-policy=static
      - kube-reserved=cpu=1
      - memory=2Gi
      - ephemeral-storage=1Gi
      - system-reserved=cpu=1
      - memory=2Gi
      - ephemeral-storage=1Gi
    nodes:
      control_plane: 1
      workers: 0
```

- [kube-reserved](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#kube-reserved) and [system-reserved](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#system-reserved) have a non-standard format that gets broken if it's split prematurely.
