### ISSUE TITLE
Feature Request: Enable 'static' cpu management policy

### ISSUE THREAD

**Issue by cloudymax** [small-hack/smol-k8s-lab#64]
## Describe the feature you'd like, and why

add the option to provide `--kubelet-arg ﻿﻿"cpu-manager-policy=static"`to k3s at node creation time.

Enables core-pinning of vcores in K3s

https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/

https://kubevirt.io/user-guide/virtual_machines/dedicated_cpu_resources/

**Comment by jessebot** [comment]
sounds good to me! you can submit a PR or wait till the next major release which should be in a week or two :)

**Comment by cloudymax** [comment]
Awesome! Thanks!

**Comment by jessebot** [comment]
You can now pass this in as a k3s extra arg:

```yaml
# a list of extra k3s args you'd like to pass in
extra_k3s_args: []
```

though in the next release this will change to:

```yaml
# a list of extra k3s args you'd like to pass in
k3s:
  extra_args: []
```

so it would be something like:

```yaml
# a list of extra k3s args you'd like to pass in
k3s:
  extra_args:
    - '--kubelet-arg ﻿﻿"cpu-manager-policy=static"'
```

Please comment if you'd like me to reopen this :)
