### ISSUE TITLE
Chore: Get rid of `apps.[].argo.part_of_app_of_apps`

### ISSUE THREAD

**Issue by jessebot** [small-hack/smol-k8s-lab#99]
## Describe the feature you'd like, and why

This feature is kinda hacky and is only used on the smol-k8s-lab backend for making sure we deploy the secret keys we need for that, but we have other ways of checking that now. Other users wouldn't have used this feature and it honestly makes things more confusing. Removing this would cut cruft from our default schema too, which would be nice for `v2.0.0`

```yaml
apps:
    argo:
      # this is the feature in question that we want to remove
      # If set to "", we'll instead use the repo, path, ref, namespace, and project_source_repos
      # else we'll skip installing this app b/c its part of another app of apps with this name.
      part_of_app_of_apps: ""
```

I don't even think most of our apps use it, so I think we can get rid of it. The only two that definitely use it are ESO and ArgoCD and both of those can easily use either `argo.directory_recursion` or we can take a `argo.secret_key` for deploying what we need there.

### External Secrets Operator
We should support gitlab, bweso, and maybe vault? Let's do that the same we do storage with an appset that templates the app directory one level up.

### ArgoCD
we should just use directory recursion here and make it clear how it works in the notes, readme of the argocd appset in the small-hack/argocd-apps repo, and the doc that goes out in this repo for argocd.

# Definition of Done

- [ ] ESO is updated in small-hack/argocd-apps AND in the README there
- [ ] ESO is updated in default_config.yaml
- [ ] ESO is updated in the docs of this repo
- [ ] ArgoCD is updated in small-hack/argocd-apps AND in the README there
- [ ] ArgoCD is updated in default_config.yaml
- [ ] ArgoCD is updated in the docs of this repo
- [ ] verify no other apps use this feature before removal
